# Generated by Django 3.0.3 on 2020-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaut.jpg', upload_to='profile_pics'),
        ),
    ]
